/* eslint-disable */
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.CmdParam', null, global);
goog.exportSymbol('proto.DataAction', null, global);
goog.exportSymbol('proto.DataParam', null, global);
goog.exportSymbol('proto.McuWrapper', null, global);
goog.exportSymbol('proto.MotorAction', null, global);
goog.exportSymbol('proto.MotorCmd', null, global);
goog.exportSymbol('proto.MotorCmdParamId', null, global);
goog.exportSymbol('proto.MotorData', null, global);
goog.exportSymbol('proto.MotorDataId', null, global);
goog.exportSymbol('proto.Unit', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MotorData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.MotorData.repeatedFields_, null);
};
goog.inherits(proto.MotorData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.MotorData.displayName = 'proto.MotorData';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.MotorData.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MotorData.prototype.toObject = function(opt_includeInstance) {
  return proto.MotorData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MotorData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MotorData.toObject = function(includeInstance, msg) {
  var f, obj = {
    action: jspb.Message.getFieldWithDefault(msg, 1, 0),
    paramsList: jspb.Message.toObjectList(msg.getParamsList(),
    proto.DataParam.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MotorData}
 */
proto.MotorData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MotorData;
  return proto.MotorData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MotorData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MotorData}
 */
proto.MotorData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.DataAction} */ (reader.readEnum());
      msg.setAction(value);
      break;
    case 2:
      var value = new proto.DataParam;
      reader.readMessage(value,proto.DataParam.deserializeBinaryFromReader);
      msg.addParams(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MotorData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MotorData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MotorData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MotorData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAction();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getParamsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.DataParam.serializeBinaryToWriter
    );
  }
};


/**
 * optional DataAction action = 1;
 * @return {!proto.DataAction}
 */
proto.MotorData.prototype.getAction = function() {
  return /** @type {!proto.DataAction} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.DataAction} value */
proto.MotorData.prototype.setAction = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * repeated DataParam params = 2;
 * @return {!Array.<!proto.DataParam>}
 */
proto.MotorData.prototype.getParamsList = function() {
  return /** @type{!Array.<!proto.DataParam>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.DataParam, 2));
};


/** @param {!Array.<!proto.DataParam>} value */
proto.MotorData.prototype.setParamsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.DataParam=} opt_value
 * @param {number=} opt_index
 * @return {!proto.DataParam}
 */
proto.MotorData.prototype.addParams = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.DataParam, opt_index);
};


proto.MotorData.prototype.clearParamsList = function() {
  this.setParamsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MotorCmd = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.MotorCmd.repeatedFields_, null);
};
goog.inherits(proto.MotorCmd, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.MotorCmd.displayName = 'proto.MotorCmd';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.MotorCmd.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MotorCmd.prototype.toObject = function(opt_includeInstance) {
  return proto.MotorCmd.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MotorCmd} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MotorCmd.toObject = function(includeInstance, msg) {
  var f, obj = {
    action: jspb.Message.getFieldWithDefault(msg, 1, 0),
    paramsList: jspb.Message.toObjectList(msg.getParamsList(),
    proto.CmdParam.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MotorCmd}
 */
proto.MotorCmd.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MotorCmd;
  return proto.MotorCmd.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MotorCmd} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MotorCmd}
 */
proto.MotorCmd.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.MotorAction} */ (reader.readEnum());
      msg.setAction(value);
      break;
    case 2:
      var value = new proto.CmdParam;
      reader.readMessage(value,proto.CmdParam.deserializeBinaryFromReader);
      msg.addParams(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MotorCmd.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MotorCmd.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MotorCmd} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MotorCmd.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAction();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getParamsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.CmdParam.serializeBinaryToWriter
    );
  }
};


/**
 * optional MotorAction action = 1;
 * @return {!proto.MotorAction}
 */
proto.MotorCmd.prototype.getAction = function() {
  return /** @type {!proto.MotorAction} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.MotorAction} value */
proto.MotorCmd.prototype.setAction = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * repeated CmdParam params = 2;
 * @return {!Array.<!proto.CmdParam>}
 */
proto.MotorCmd.prototype.getParamsList = function() {
  return /** @type{!Array.<!proto.CmdParam>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.CmdParam, 2));
};


/** @param {!Array.<!proto.CmdParam>} value */
proto.MotorCmd.prototype.setParamsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.CmdParam=} opt_value
 * @param {number=} opt_index
 * @return {!proto.CmdParam}
 */
proto.MotorCmd.prototype.addParams = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.CmdParam, opt_index);
};


proto.MotorCmd.prototype.clearParamsList = function() {
  this.setParamsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.McuWrapper = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.McuWrapper.oneofGroups_);
};
goog.inherits(proto.McuWrapper, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.McuWrapper.displayName = 'proto.McuWrapper';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.McuWrapper.oneofGroups_ = [[2,3]];

/**
 * @enum {number}
 */
proto.McuWrapper.ContentCase = {
  CONTENT_NOT_SET: 0,
  MOTORDATA: 2,
  MOTORCMD: 3
};

/**
 * @return {proto.McuWrapper.ContentCase}
 */
proto.McuWrapper.prototype.getContentCase = function() {
  return /** @type {proto.McuWrapper.ContentCase} */(jspb.Message.computeOneofCase(this, proto.McuWrapper.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.McuWrapper.prototype.toObject = function(opt_includeInstance) {
  return proto.McuWrapper.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.McuWrapper} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.McuWrapper.toObject = function(includeInstance, msg) {
  var f, obj = {
    uuid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    motordata: (f = msg.getMotordata()) && proto.MotorData.toObject(includeInstance, f),
    motorcmd: (f = msg.getMotorcmd()) && proto.MotorCmd.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.McuWrapper}
 */
proto.McuWrapper.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.McuWrapper;
  return proto.McuWrapper.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.McuWrapper} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.McuWrapper}
 */
proto.McuWrapper.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUuid(value);
      break;
    case 2:
      var value = new proto.MotorData;
      reader.readMessage(value,proto.MotorData.deserializeBinaryFromReader);
      msg.setMotordata(value);
      break;
    case 3:
      var value = new proto.MotorCmd;
      reader.readMessage(value,proto.MotorCmd.deserializeBinaryFromReader);
      msg.setMotorcmd(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.McuWrapper.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.McuWrapper.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.McuWrapper} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.McuWrapper.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUuid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMotordata();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.MotorData.serializeBinaryToWriter
    );
  }
  f = message.getMotorcmd();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.MotorCmd.serializeBinaryToWriter
    );
  }
};


/**
 * optional string uuid = 1;
 * @return {string}
 */
proto.McuWrapper.prototype.getUuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.McuWrapper.prototype.setUuid = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional MotorData motorData = 2;
 * @return {?proto.MotorData}
 */
proto.McuWrapper.prototype.getMotordata = function() {
  return /** @type{?proto.MotorData} */ (
    jspb.Message.getWrapperField(this, proto.MotorData, 2));
};


/** @param {?proto.MotorData|undefined} value */
proto.McuWrapper.prototype.setMotordata = function(value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.McuWrapper.oneofGroups_[0], value);
};


proto.McuWrapper.prototype.clearMotordata = function() {
  this.setMotordata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.McuWrapper.prototype.hasMotordata = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional MotorCmd motorCmd = 3;
 * @return {?proto.MotorCmd}
 */
proto.McuWrapper.prototype.getMotorcmd = function() {
  return /** @type{?proto.MotorCmd} */ (
    jspb.Message.getWrapperField(this, proto.MotorCmd, 3));
};


/** @param {?proto.MotorCmd|undefined} value */
proto.McuWrapper.prototype.setMotorcmd = function(value) {
  jspb.Message.setOneofWrapperField(this, 3, proto.McuWrapper.oneofGroups_[0], value);
};


proto.McuWrapper.prototype.clearMotorcmd = function() {
  this.setMotorcmd(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.McuWrapper.prototype.hasMotorcmd = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.DataParam = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.DataParam, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.DataParam.displayName = 'proto.DataParam';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.DataParam.prototype.toObject = function(opt_includeInstance) {
  return proto.DataParam.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.DataParam} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.DataParam.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    value: +jspb.Message.getFieldWithDefault(msg, 2, 0.0),
    unit: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.DataParam}
 */
proto.DataParam.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.DataParam;
  return proto.DataParam.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.DataParam} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.DataParam}
 */
proto.DataParam.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.MotorDataId} */ (reader.readEnum());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setValue(value);
      break;
    case 3:
      var value = /** @type {!proto.Unit} */ (reader.readEnum());
      msg.setUnit(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.DataParam.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.DataParam.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.DataParam} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.DataParam.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getValue();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getUnit();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
};


/**
 * optional MotorDataId id = 1;
 * @return {!proto.MotorDataId}
 */
proto.DataParam.prototype.getId = function() {
  return /** @type {!proto.MotorDataId} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.MotorDataId} value */
proto.DataParam.prototype.setId = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional double value = 2;
 * @return {number}
 */
proto.DataParam.prototype.getValue = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 2, 0.0));
};


/** @param {number} value */
proto.DataParam.prototype.setValue = function(value) {
  jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional Unit unit = 3;
 * @return {!proto.Unit}
 */
proto.DataParam.prototype.getUnit = function() {
  return /** @type {!proto.Unit} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {!proto.Unit} value */
proto.DataParam.prototype.setUnit = function(value) {
  jspb.Message.setProto3EnumField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.CmdParam = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.CmdParam, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.CmdParam.displayName = 'proto.CmdParam';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.CmdParam.prototype.toObject = function(opt_includeInstance) {
  return proto.CmdParam.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.CmdParam} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CmdParam.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    value: +jspb.Message.getFieldWithDefault(msg, 2, 0.0),
    unit: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.CmdParam}
 */
proto.CmdParam.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.CmdParam;
  return proto.CmdParam.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.CmdParam} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.CmdParam}
 */
proto.CmdParam.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.MotorCmdParamId} */ (reader.readEnum());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setValue(value);
      break;
    case 3:
      var value = /** @type {!proto.Unit} */ (reader.readEnum());
      msg.setUnit(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.CmdParam.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.CmdParam.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.CmdParam} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CmdParam.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getValue();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getUnit();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
};


/**
 * optional MotorCmdParamId id = 1;
 * @return {!proto.MotorCmdParamId}
 */
proto.CmdParam.prototype.getId = function() {
  return /** @type {!proto.MotorCmdParamId} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.MotorCmdParamId} value */
proto.CmdParam.prototype.setId = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional double value = 2;
 * @return {number}
 */
proto.CmdParam.prototype.getValue = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 2, 0.0));
};


/** @param {number} value */
proto.CmdParam.prototype.setValue = function(value) {
  jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional Unit unit = 3;
 * @return {!proto.Unit}
 */
proto.CmdParam.prototype.getUnit = function() {
  return /** @type {!proto.Unit} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {!proto.Unit} value */
proto.CmdParam.prototype.setUnit = function(value) {
  jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * @enum {number}
 */
proto.DataAction = {
  UKNONWN_ACTION: 0,
  GET: 1,
  RESULT: 2
};

/**
 * @enum {number}
 */
proto.MotorAction = {
  UNKNOWN: 0,
  BRAKE: 1,
  FREEWHEEL: 2,
  RUN: 3,
  GOTO_POS: 4
};

/**
 * @enum {number}
 */
proto.MotorDataId = {
  UNKNOWN_ID: 0,
  UUID: 1,
  VERSION: 2,
  MFG_DATE_YYYYMMDD: 3,
  MFG_ID: 4,
  MODEL_ID: 5,
  STEP_COUNT: 6,
  INDUCTANCE: 8,
  CUR_POS: 12,
  CUR_AMP: 13,
  CUR_VOLT: 14
};

/**
 * @enum {number}
 */
proto.Unit = {
  UNKNOWN_UNIT: 0,
  STRING: 1,
  BOOLEAN: 2,
  INTEGER: 3,
  DOUBLE: 4,
  SECOND: 5,
  DEGREE: 6,
  AMP: 7,
  VOLT: 8,
  NEWTON: 9,
  UHENRY: 10
};

/**
 * @enum {number}
 */
proto.MotorCmdParamId = {
  UNKNOWN_PARAM: 0,
  CLOCKWISE: 1,
  POSITION: 2,
  VELOCITY: 3,
  ACCEL: 4,
  HOLD_TORQUE: 5,
  BREAKAWAY: 6,
  MIN_CURRENT_LIMIT: 7,
  MAX_CURRENT_LIMIT: 8,
  MIN_VOLT_VELOCITY: 9,
  MAX_VOLT_VELOCITY: 10,
  MIN_VOLTAGE_LIMIT: 11,
  MAX_VOLTAGE_LIMIT: 12
};

goog.object.extend(exports, proto);
