/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.Drive');

goog.require('jspb.Message');
goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Drive = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Drive, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.Drive.displayName = 'proto.Drive';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Drive.prototype.toObject = function(opt_includeInstance) {
  return proto.Drive.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Drive} msg The msg instance to transform.
 * @return {!Object}
 */
proto.Drive.toObject = function(includeInstance, msg) {
  var f, obj = {
    velocity: msg.getVelocity(),
    direction: msg.getDirection(),
    acceleration: msg.getAcceleration(),
    distance: msg.getDistance(),
    edgedistance: msg.getEdgedistance(),
    edgeside: msg.getEdgeside()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Drive}
 */
proto.Drive.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Drive;
  return proto.Drive.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Drive} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Drive}
 */
proto.Drive.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setVelocity(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDirection(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setAcceleration(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setDistance(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setEdgedistance(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setEdgeside(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.Drive} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.Drive.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Drive.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.Drive.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getVelocity();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = this.getDirection();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = this.getAcceleration();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = this.getDistance();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = this.getEdgedistance();
  if (f !== 0.0) {
    writer.writeDouble(
      5,
      f
    );
  }
  f = this.getEdgeside();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.Drive} The clone.
 */
proto.Drive.prototype.cloneMessage = function() {
  return /** @type {!proto.Drive} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional double velocity = 1;
 * @return {number}
 */
proto.Drive.prototype.getVelocity = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 1, 0));
};


/** @param {number} value  */
proto.Drive.prototype.setVelocity = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string direction = 2;
 * @return {string}
 */
proto.Drive.prototype.getDirection = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.Drive.prototype.setDirection = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional double acceleration = 3;
 * @return {number}
 */
proto.Drive.prototype.getAcceleration = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 3, 0));
};


/** @param {number} value  */
proto.Drive.prototype.setAcceleration = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional double distance = 4;
 * @return {number}
 */
proto.Drive.prototype.getDistance = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 4, 0));
};


/** @param {number} value  */
proto.Drive.prototype.setDistance = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional double edgeDistance = 5;
 * @return {number}
 */
proto.Drive.prototype.getEdgedistance = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 5, 0));
};


/** @param {number} value  */
proto.Drive.prototype.setEdgedistance = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional string edgeSide = 6;
 * @return {string}
 */
proto.Drive.prototype.getEdgeside = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 6, ""));
};


/** @param {string} value  */
proto.Drive.prototype.setEdgeside = function(value) {
  jspb.Message.setField(this, 6, value);
};


