/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.Orbit');

goog.require('jspb.Message');
goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Orbit = function (opt_data) {
	jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Orbit, jspb.Message);
if (goog.DEBUG && !COMPILED) {
	proto.Orbit.displayName = 'proto.Orbit';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
	/**
	 * Creates an object representation of this proto suitable for use in Soy templates.
	 * Field names that are reserved in JavaScript and will be renamed to pb_name.
	 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
	 * For the list of reserved names please see:
	 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
	 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
	 *     for transitional soy proto support: http://goto/soy-param-migration
	 * @return {!Object}
	 */
	proto.Orbit.prototype.toObject = function (opt_includeInstance) {
		return proto.Orbit.toObject(opt_includeInstance, this);
	};


	/**
	 * Static version of the {@see toObject} method.
	 * @param {boolean|undefined} includeInstance Whether to include the JSPB
	 *     instance for transitional soy proto support:
	 *     http://goto/soy-param-migration
	 * @param {!proto.Orbit} msg The msg instance to transform.
	 * @return {!Object}
	 */
	proto.Orbit.toObject = function (includeInstance, msg) {
		var f, obj = {
			velocity: +jspb.Message.getFieldWithDefault(msg, 1, 0.0),
			direction: jspb.Message.getFieldWithDefault(msg, 2, ""),
			acceleration: +jspb.Message.getFieldWithDefault(msg, 3, 0.0),
			degrees: +jspb.Message.getFieldWithDefault(msg, 4, 0.0)
		};

		if (includeInstance) {
			obj.$jspbMessageInstance = msg;
		}
		return obj;
	};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Orbit}
 */
proto.Orbit.deserializeBinary = function (bytes) {
	var reader = new jspb.BinaryReader(bytes);
	var msg = new proto.Orbit;
	return proto.Orbit.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Orbit} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Orbit}
 */
proto.Orbit.deserializeBinaryFromReader = function (msg, reader) {
	while (reader.nextField()) {
		if (reader.isEndGroup()) {
			break;
		}
		var field = reader.getFieldNumber();
		switch (field) {
			case 1:
				var value = /** @type {number} */ (reader.readDouble());
				msg.setVelocity(value);
				break;
			case 2:
				var value = /** @type {string} */ (reader.readString());
				msg.setDirection(value);
				break;
			case 3:
				var value = /** @type {number} */ (reader.readDouble());
				msg.setAcceleration(value);
				break;
			case 4:
				var value = /** @type {number} */ (reader.readDouble());
				msg.setDegrees(value);
				break;
			default:
				reader.skipField();
				break;
		}
	}
	return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Orbit.prototype.serializeBinary = function () {
	var writer = new jspb.BinaryWriter();
	proto.Orbit.serializeBinaryToWriter(this, writer);
	return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Orbit} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.Orbit.serializeBinaryToWriter = function (message, writer) {
	var f = undefined;
	f = message.getVelocity();
	if (f !== 0.0) {
		writer.writeDouble(
			1,
			f
		);
	}
	f = message.getDirection();
	if (f.length > 0) {
		writer.writeString(
			2,
			f
		);
	}
	f = message.getAcceleration();
	if (f !== 0.0) {
		writer.writeDouble(
			3,
			f
		);
	}
	f = message.getDegrees();
	if (f !== 0.0) {
		writer.writeDouble(
			4,
			f
		);
	}
};


/**
 * optional double velocity = 1;
 * @return {number}
 */
proto.Orbit.prototype.getVelocity = function () {
	return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 1, 0.0));
};


/** @param {number} value */
proto.Orbit.prototype.setVelocity = function (value) {
	jspb.Message.setField(this, 1, value);
};


/**
 * optional string direction = 2;
 * @return {string}
 */
proto.Orbit.prototype.getDirection = function () {
	return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.Orbit.prototype.setDirection = function (value) {
	jspb.Message.setField(this, 2, value);
};


/**
 * optional double acceleration = 3;
 * @return {number}
 */
proto.Orbit.prototype.getAcceleration = function () {
	return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 3, 0.0));
};


/** @param {number} value */
proto.Orbit.prototype.setAcceleration = function (value) {
	jspb.Message.setField(this, 3, value);
};


/**
 * optional double degrees = 4;
 * @return {number}
 */
proto.Orbit.prototype.getDegrees = function () {
	return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 4, 0.0));
};


/** @param {number} value */
proto.Orbit.prototype.setDegrees = function (value) {
	jspb.Message.setField(this, 4, value);
};


